### ISSUE TITLE
Error on Sublime Startup

### ISSUE THREAD

**Issue by sgessler** [SublimeText/Ceedling#2]
Anybody else getting this error in the console on startup?

`reloading plugin Ceedling.OpenCeedlingFile
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 853, in _load_module
  File "<frozen importlib._bootstrap>", line 980, in get_code
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/sge/Library/Application Support/Sublime Text 3/Packages/Ceedling/OpenCeedlingFile.py", line 25
    print "Basename: " + base_name
                     ^
SyntaxError: invalid syntax
plugins loaded
Unable to fetch update url contents
Package Control: Skipping automatic upgrade, last run at 2017-05-12 12:40:37, next run at 2017-05-12 13:40:37 or after`

**Comment by FichteFoll** [comment]
The package uses Python 2 `print` syntax. It has to be updated to work on ST3.

**Comment by pajacobson** [comment]
Resolved by PR #7
